import "./globals.css";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { FirebaseAuthProvider } from "@/auth/context/auth-context";

export const metadata: Metadata = {
  title: "AI Image Generator App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <FirebaseAuthProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={cn(GeistSans.className, "dark:bg-white p-1 ")}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
            storageKey="discord-theme"
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </FirebaseAuthProvider>
  );
}
